"""Productization Phase 10: the control-plane database backends (api/db.py)."""

from __future__ import annotations

import sqlite3
from pathlib import Path

import pytest
from _pg_mode import POSTGRES_URL

from api.control_db import ControlDB, _resolve_backend
from api.db import (
    PostgresBackend,
    PostgresDialect,
    Row,
    SqliteBackend,
    _ident,
    schema_for_path,
    translate_placeholders,
)


class TestPlaceholderTranslation:
    @pytest.mark.parametrize(
        ("sql", "expected"),
        [
            ("SELECT * FROM t WHERE a = ? AND b = ?", "SELECT * FROM t WHERE a = %s AND b = %s"),
            ("UPDATE t SET n = :n WHERE k = :key", "UPDATE t SET n = %(n)s WHERE k = %(key)s"),
            (
                "SELECT '?', ':x', 'a%b' FROM t WHERE c = ?",
                "SELECT '?', ':x', 'a%%b' FROM t WHERE c = %s",
            ),
            ("SELECT ?::jsonb", "SELECT %s::jsonb"),
            ("SELECT a FROM t WHERE b LIKE '%' || ?", "SELECT a FROM t WHERE b LIKE '%%' || %s"),
            ('SELECT "col?" FROM t', 'SELECT "col?" FROM t'),
            ("SELECT x % 2 FROM t", "SELECT x %% 2 FROM t"),
            # Comments: a `?` / `:name` inside is text, not a parameter.
            (
                "SELECT a -- why? :later\nFROM t WHERE b = ?",
                "SELECT a -- why? :later\nFROM t WHERE b = %s",
            ),
            (
                "SELECT /* is it? :x */ a FROM t WHERE b = :b",
                "SELECT /* is it? :x */ a FROM t WHERE b = %(b)s",
            ),
            ("SELECT /* 100% */ ?", "SELECT /* 100%% */ %s"),
            # Escaped quote inside a literal does not end it.
            ("SELECT 'it''s ?' FROM t WHERE a = ?", "SELECT 'it''s ?' FROM t WHERE a = %s"),
            # Dollar-quoted bodies (anonymous and tagged).
            ("DO $$ SELECT ?; $$", "DO $$ SELECT ?; $$"),
            ("SELECT $fn$ :x ? $fn$, ?", "SELECT $fn$ :x ? $fn$, %s"),
            ("SELECT ':a::b' || ?::text", "SELECT ':a::b' || %s::text"),
        ],
    )
    def test_translates_outside_quotes_only(self, sql: str, expected: str) -> None:
        assert translate_placeholders(sql) == expected


class TestRowParity:
    def test_reads_like_sqlite3_row(self) -> None:
        row = Row(("a", "b"), (1, "x"))
        assert row["a"] == 1 and row[1] == "x"
        assert row.keys() == ["a", "b"]
        assert dict(row) == {"a": 1, "b": "x"}
        assert tuple(row) == (1, "x") and len(row) == 2
        a, b = row
        assert (a, b) == (1, "x")

    def test_equality_matches_sqlite3_row(self) -> None:
        conn = sqlite3.connect(":memory:")
        conn.row_factory = sqlite3.Row
        first, second = conn.execute("SELECT 1 AS a UNION ALL SELECT 1").fetchall()
        assert first == second and first != (1,)
        assert Row(("a",), (1,)) == Row(("a",), (1,))
        assert Row(("a",), (1,)) != Row(("b",), (1,))
        assert Row(("a",), (1,)) != (1,)
        assert len({Row(("a",), (1,)), Row(("a",), (1,))}) == 1


class TestPostgresDdl:
    def test_identity_and_double_precision(self) -> None:
        ddl = PostgresDialect().schema(
            "CREATE TABLE t (id INTEGER PRIMARY KEY AUTOINCREMENT, score REAL, " "realm TEXT);"
        )
        assert "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" in ddl
        assert "score DOUBLE PRECISION" in ddl
        assert "realm TEXT" in ddl  # word boundary: not a REAL column
        assert "CREATE OR REPLACE FUNCTION julianday" in ddl


class TestIdentifiers:
    @pytest.mark.parametrize("name", ["public", "t_0123abcd", "hydra_prod"])
    def test_safe_names_pass(self, name: str) -> None:
        assert _ident(name) == name

    @pytest.mark.parametrize("name", ["", "Public", "a;drop schema x", "x y", '"x"', "1abc"])
    def test_unsafe_names_are_rejected(self, name: str) -> None:
        with pytest.raises(ValueError, match="unsafe SQL identifier"):
            _ident(name)

    def test_schema_for_path_is_stable_and_safe(self, tmp_path: Path) -> None:
        name = schema_for_path(tmp_path / "control.db")
        assert name == schema_for_path(tmp_path / "control.db")
        assert name != schema_for_path(tmp_path / "other.db")
        assert _ident(name) == name


@pytest.mark.skipif(bool(POSTGRES_URL), reason="the Postgres test mode replaces the resolver")
class TestBackendSelection:
    def test_no_url_is_the_sqlite_file(self, tmp_path: Path) -> None:
        backend = _resolve_backend(tmp_path / "control.db", None)
        assert isinstance(backend, SqliteBackend)
        assert backend.path == tmp_path / "control.db"

    def test_a_url_is_postgres_in_the_public_schema(self, tmp_path: Path) -> None:
        # Nothing connects until first use (the public schema needs no setup).
        backend = _resolve_backend(tmp_path / "control.db", "postgresql://u@127.0.0.1:1/x")
        assert isinstance(backend, PostgresBackend)
        assert backend.schema == "public" and backend.dialect.name == "postgres"


@pytest.mark.skipif(not POSTGRES_URL, reason="needs HYDRA_TEST_DATABASE_URL")
class TestOnPostgres:
    def test_schema_isolation_between_instances(self, tmp_path: Path) -> None:
        first = ControlDB(tmp_path / "a.db")
        second = ControlDB(tmp_path / "b.db")
        account_id = first.create_account(email="iso@example.com")
        assert first.get_account(account_id) is not None
        assert second.get_account(account_id) is None

    def test_writes_are_committed_when_the_block_ends(self, tmp_path: Path) -> None:
        """Seen from an independent session (a pooled one could see its own
        uncommitted work): connect() commits on a normal exit, rolls back
        on an exception."""
        import psycopg

        db = ControlDB(tmp_path / "d.db")
        committed = db.create_account(email="committed@example.com")
        with pytest.raises(RuntimeError), db._connect() as conn:
            conn.execute(
                "UPDATE accounts SET email = 'rolled-back@example.com' WHERE account_id = ?",
                (committed,),
            )
            raise RuntimeError("abort")

        backend = db.backend
        if not isinstance(backend, PostgresBackend):
            pytest.fail("expected the Postgres backend")
        with psycopg.connect(str(POSTGRES_URL)) as other:
            other.execute("SELECT set_config('search_path', %s, true)", (backend.schema,))
            row = other.execute(
                "SELECT email FROM accounts WHERE account_id = %s", (committed,)
            ).fetchone()
        assert row == ("committed@example.com",)

    def test_null_safe_equality_and_booleans_round_trip(self, tmp_path: Path) -> None:
        db = ControlDB(tmp_path / "c.db")
        with db._connect() as conn:
            assert conn.execute("SELECT NULL IS NOT DISTINCT FROM ?", (None,)).fetchone()[0]
            assert conn.execute("SELECT ? = 1", (True,)).fetchone()[0]
            assert conn.execute("SELECT julianday('1970-01-01T00:00:00+00:00')").fetchone()[
                0
            ] == pytest.approx(2440587.5)
            assert conn.execute("SELECT instr('hydra', 'dr')").fetchone()[0] == 3
