"""Productization Phase 10: the control plane's database backends.

`ControlDB` runs on either backend with the same SQL:

- **SQLite** (a local file) — the CLI, local development and the fast test
  suite; the single-node mode the roadmap keeps viable.
- **PostgreSQL** (`HYDRA_API_DATABASE_URL`, e.g. DigitalOcean managed
  Postgres 18 with `sslmode=require`) — the production API: concurrent
  multi-tenant writers.

The SQL is written once, portably: `?` / `:name` placeholders,
`INSERT ... ON CONFLICT`, `COALESCE`, `substr`, `LIMIT ? OFFSET ?`, and
SQLite's `julianday()` / `instr()`, which the Postgres schema defines with
SQLite's semantics. The few statements that can't be shared exist as two
complete literal variants (never assembled from fragments); the dialect
object covers the write lock, schema DDL, column introspection and the
health query.

Postgres specifics, chosen for parity with SQLite's behavior:
- placeholders are translated `?` -> `%s`, `:name` -> `%(name)s` (quoted
  strings and `::` casts are left alone; a literal `%` is escaped);
- parameters are bound client-side (psycopg `ClientCursor`), so a
  `? IS NULL` test works with `None` exactly as in SQLite;
- Python booleans are stored as 0/1 in integer columns, as SQLite does;
- rows support `row["col"]`, `row[0]`, `row.keys()` and `dict(row)`, like
  `sqlite3.Row`;
- one connection pool per database URL, shared by every `ControlDB` on it;
  each checkout sets the `search_path` to the instance's schema (tests get
  a schema each; production uses `public`).
"""

from __future__ import annotations

import hashlib
import re
import sqlite3
from collections.abc import Iterator
from contextlib import contextmanager
from functools import lru_cache
from pathlib import Path
from typing import Any

from core.store import connect_sqlite

_SAFE_IDENTIFIER = re.compile(r"^[a-z_][a-z0-9_]{0,62}$")
_NAMED_PARAM = re.compile(r"[A-Za-z_]\w*")


# SQLite built-ins the shared SQL uses, defined in Postgres with SQLite's
# exact semantics so the queries stay identical on both backends. Neither
# name exists in Postgres, so nothing built-in is shadowed.
_PG_COMPAT_FUNCTIONS = """
CREATE OR REPLACE FUNCTION julianday(ts text) RETURNS double precision
    LANGUAGE sql STABLE STRICT
    AS $$ SELECT extract(epoch FROM ts::timestamptz) / 86400.0 + 2440587.5 $$;
CREATE OR REPLACE FUNCTION instr(haystack text, needle text) RETURNS integer
    LANGUAGE sql IMMUTABLE STRICT
    AS $$ SELECT strpos(haystack, needle) $$;
"""


class SqliteDialect:
    name = "sqlite"
    integrity_errors: tuple[type[Exception], ...] = (sqlite3.IntegrityError,)
    # A real read of the database file (a constant like SELECT 1 is answered
    # without opening it — see ControlDB.ping).
    ping_sql = "SELECT count(*) FROM sqlite_master"

    def begin_write(self, conn: Any, key: str) -> None:
        """Take the database write lock before reading what will be
        replaced (the whole file, on SQLite)."""
        del key
        conn.execute("BEGIN IMMEDIATE")

    def columns(self, conn: Any, table: str) -> set[str]:
        return {row[0] for row in conn.execute("SELECT name FROM pragma_table_info(?)", (table,))}

    def schema(self, sqlite_ddl: str) -> str:
        return sqlite_ddl


class PostgresDialect:
    name = "postgres"
    ping_sql = "SELECT count(*) FROM information_schema.tables"

    @property
    def integrity_errors(self) -> tuple[type[Exception], ...]:
        import psycopg

        return (psycopg.IntegrityError,)

    def begin_write(self, conn: Any, key: str) -> None:
        """A transaction-scoped advisory lock per logical resource, held
        until commit: the same "read, then write" exclusivity as SQLite's
        BEGIN IMMEDIATE, without locking unrelated writers."""
        conn.execute("SELECT pg_advisory_xact_lock(hashtextextended(?, 0))", (key,))

    def columns(self, conn: Any, table: str) -> set[str]:
        rows = conn.execute(
            "SELECT column_name FROM information_schema.columns "
            "WHERE table_schema = current_schema() AND table_name = ?",
            (table,),
        ).fetchall()
        return {row[0] for row in rows}

    def schema(self, sqlite_ddl: str) -> str:
        """The SQLite DDL, translated where Postgres differs (identity
        columns; DOUBLE PRECISION, since Postgres REAL is single precision),
        preceded by the SQLite-compatible functions the shared SQL uses."""
        ddl = _PG_COMPAT_FUNCTIONS + sqlite_ddl.replace(
            "INTEGER PRIMARY KEY AUTOINCREMENT",
            "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        )
        return re.sub(r"\bREAL\b", "DOUBLE PRECISION", ddl)


def _ident(name: str) -> str:
    if not _SAFE_IDENTIFIER.match(name):
        raise ValueError(f"unsafe SQL identifier: {name!r}")
    return name


@lru_cache(maxsize=4096)
def translate_placeholders(sql: str) -> str:
    """`?` -> `%s`, `:name` -> `%(name)s`, `%` -> `%%`, outside quoted
    strings; `::` casts are kept."""
    out: list[str] = []
    i, quote = 0, ""
    while i < len(sql):
        ch = sql[i]
        if quote:
            out.append("%%" if ch == "%" else ch)
            if ch == quote:
                quote = ""
        elif ch in ("'", '"'):
            quote = ch
            out.append(ch)
        elif ch == "?":
            out.append("%s")
        elif ch == "%":
            out.append("%%")
        elif ch == ":" and sql[i + 1 : i + 2] == ":":
            out.append("::")
            i += 1
        elif ch == ":" and (named := _NAMED_PARAM.match(sql, i + 1)):
            out.append(f"%({named.group(0)})s")
            i += len(named.group(0))
        else:
            out.append(ch)
        i += 1
    return "".join(out)


class Row:
    """A result row readable like `sqlite3.Row`."""

    __slots__ = ("_names", "_values")

    def __init__(self, names: tuple[str, ...], values: tuple[Any, ...]) -> None:
        self._names = names
        self._values = values

    def keys(self) -> list[str]:
        return list(self._names)

    def __getitem__(self, key: int | str) -> Any:
        if isinstance(key, int):
            return self._values[key]
        return self._values[self._names.index(key)]

    def __iter__(self) -> Iterator[Any]:
        return iter(self._values)

    def __len__(self) -> int:
        return len(self._values)

    def __eq__(self, other: object) -> bool:
        # As sqlite3.Row: equal to a row with the same columns and values.
        if not isinstance(other, Row):
            return NotImplemented
        return self._names == other._names and self._values == other._values

    def __hash__(self) -> int:
        return hash((self._names, self._values))


class _PgConnection:
    """What ControlDB code expects of a connection: execute / executemany
    returning a cursor, and executescript."""

    def __init__(self, conn: Any) -> None:
        self._conn = conn

    def execute(self, sql: str, params: Any = None) -> Any:
        if params is None or (not isinstance(params, dict) and len(params) == 0):
            return self._conn.execute(sql)
        return self._conn.execute(translate_placeholders(sql), params)

    def executemany(self, sql: str, seq: Any) -> Any:
        cursor = self._conn.cursor()
        cursor.executemany(translate_placeholders(sql), list(seq))
        return cursor

    def executescript(self, script: str) -> None:
        self._conn.execute(script)


def _row_factory(cursor: Any) -> Any:
    names = tuple(column.name for column in (cursor.description or ()))
    return lambda values: Row(names, tuple(values))


@lru_cache(maxsize=8)
def _pool(url: str) -> Any:
    import psycopg
    from psycopg import ClientCursor
    from psycopg.adapt import Dumper
    from psycopg_pool import ConnectionPool

    class BoolAsInt(Dumper):
        oid = psycopg.adapters.types["int8"].oid

        def dump(self, obj: Any) -> bytes:
            return b"1" if obj else b"0"

    def configure(conn: Any) -> None:
        conn.adapters.register_dumper(bool, BoolAsInt)

    return ConnectionPool(
        url,
        min_size=1,
        max_size=10,
        open=True,
        configure=configure,
        kwargs={"cursor_factory": ClientCursor, "row_factory": _row_factory},
    )


class Backend:
    """How a ControlDB reaches its database."""

    def __init__(self, dialect: SqliteDialect | PostgresDialect) -> None:
        self.dialect = dialect

    @contextmanager
    def connect(self) -> Iterator[Any]:
        raise NotImplementedError


class SqliteBackend(Backend):
    def __init__(self, path: Path) -> None:
        super().__init__(SqliteDialect())
        self.path = path

    @contextmanager
    def connect(self) -> Iterator[Any]:
        conn = connect_sqlite(self.path)
        try:
            yield conn
            conn.commit()
        except BaseException:
            conn.rollback()
            raise
        finally:
            conn.close()


class PostgresBackend(Backend):
    def __init__(self, url: str, *, schema: str = "public") -> None:
        super().__init__(PostgresDialect())
        self.url = url
        self.schema = _ident(schema)
        if self.schema != "public":
            from psycopg import sql

            with _pool(url).connection() as conn:
                conn.execute(
                    sql.SQL("CREATE SCHEMA IF NOT EXISTS {}").format(sql.Identifier(self.schema))
                )

    @contextmanager
    def connect(self) -> Iterator[Any]:
        with _pool(self.url).connection() as conn:
            conn.execute("SELECT set_config('search_path', %s, false)", (self.schema,))
            yield _PgConnection(conn)


def schema_for_path(path: Path) -> str:
    """A stable, safe schema name per database path (test isolation)."""
    return "t_" + hashlib.sha256(str(path).encode()).hexdigest()[:24]
